all:
	g++ AgrItens.cpp -Wall -o AgrItens -std=c++11 -pthread

run1:
	make
	./AgrItens 20 100 4 1 100

run2:
	make
	./AgrItens 40 400 8 4 1000000
r10:
	./AgrItens 50 800 100 10 2000

r5:
	./AgrItens 50 800 100 5 2000

r1:
	./AgrItens 50 800 100 1 2000

semprint:
	g++ AgrItens.cpp -Wall -o AgrItens -std=c++11 -pthread -D semprint
